"""Add username to User model

Revision ID: 19e50e996279
Revises: 33a2f60380ef
Create Date: 2026-01-22 23:13:34.398644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e50e996279'
down_revision = '33a2f60380ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable first
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    
    # 2. Populate username from email (take everything before @)
    # Using SQL directly for speed and simplicity in migration
    op.execute("UPDATE users SET username = split_part(email, '@', 1)")
    
    # 3. Ensure no nulls remain (fallback to 'user_' + id)
    op.execute("UPDATE users SET username = 'user_' || id WHERE username IS NULL OR username = ''")
    
    # 4. Now set it to NOT NULL
    op.alter_column('users', 'username', nullable=False)
    
    # 5. Create the index
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
