"""Add master data model

Revision ID: 33a2f60380ef
Revises: 22845a99f8b0
Create Date: 2026-01-22 15:01:45.940820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a2f60380ef'
down_revision = '22845a99f8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_time_minutes', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.drop_column('response_time_minutes')

    # ### end Alembic commands ###
