"""Add image_url to ticket notes

Revision ID: 51d5980345eb
Revises: c15213f14ccf
Create Date: 2026-01-25 16:21:33.454940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d5980345eb'
down_revision = 'c15213f14ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_notes', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
